### ISSUE TITLE
change the error icon in the notification message to "x"

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-fds-design#31]
change the error icon globally in the design system form this:
![Capture-error-icon-current](https://github.com/bcgov/nr-fds-design/assets/121979429/2de9bfc5-86d9-47c0-9bfe-2c04e97bdc2f)

to this:
![Image](https://github.com/bcgov/nr-fds-design/assets/121979429/60f0a370-f6f9-4a21-9ffc-adf992db49fd)

**Comment by jackwingsam** [comment]
Duplicate ticket. 
I added OlgaLiber2's original ticket https://github.com/bcgov/nr-theme/issues/157 to FDS Design.
